name: Snapshot

on:
  push:
    tags:
      - 'snapshot/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install ARM tools
      run: make arm_sdk_install

    - name: Set build variables
      run: |
        GIT_VER=${GITHUB_REF##*/}
        GIT_TAG=${GITHUB_REF##refs/tags/}
        if [[ ${GIT_VER} =~ ^[0-9]+[.][0-9]+[.][0-9]+[-][A-Za-z0-9]+ ]]
        then
          GIT_PRE="${GIT_VER##*-}"
        else
          GIT_PRE="${GIT_VER}"
        fi
        echo "GIT_VER=${GIT_VER}" >> ${GITHUB_ENV}
        echo "GIT_TAG=${GIT_TAG}" >> ${GITHUB_ENV}
        echo "GIT_PRE=${GIT_PRE}" >> ${GITHUB_ENV}
        cat ${GITHUB_ENV}

    - name: Build HEX files for unified targets
      run: make unified FC_VER_SUFFIX="${{ env.GIT_PRE }}" FLASH_CONFIG_ERASE=yes

    - name: Create Snapshot
      run: |
        .github/scripts/extract-release-notes.py "${{ env.GIT_VER }}" Releases.md > Notes.md
        gh release create ${{ env.GIT_TAG }} --prerelease --notes-file Notes.md --title "Rotorflight Snapshot ${{ env.GIT_VER }}" obj/*.hex
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

